# Changes here will be overwritten by Copier
_commit: 1.4.1
_src_path: https://github.com/pawamoy/copier-uv.git
author_email: vandy.goel23@gmail.com
author_fullname: vandyG
author_username: vandyG
copyright_date: '2024'
copyright_holder: vandyG
copyright_holder_email: vandy.goel23@gmail.com
copyright_license: MIT License
insiders: false
project_description: probstats-project
project_name: probstats-project
python_package_command_line_name: probstats-project
python_package_distribution_name: probstats-project
python_package_import_name: probstats_project
repository_name: probstats-project
repository_namespace: vandyG
repository_provider: github.com

